version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Monte le code source pour le hot reload
      - /app/node_modules  # Exclut node_modules local pour éviter les conflits
    environment:
      - NODE_ENV=development
